apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaler-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scaler-role
rules:
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scaler-rb
subjects:
- kind: ServiceAccount
  name: scaler-sa
roleRef:
  kind: Role
  name: scaler-role
  apiGroup: rbac.authorization.k8s.io